/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaceLayer;

import BusinessLogicLayer.Customer;
import BusinessLogicLayer.DataManager;
import BusinessLogicLayer.Validations;

/**
 *
 * @author arsalan
 */
public class AddCustomer extends javax.swing.JPanel {

    private Validations validation;
    private DataManager dataManager;
    private DialogBox dialog;

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        validation = new Validations();
        dataManager = DataManager.getInstance();
        dialog = new DialogBox();
        clearValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName_Add = new javax.swing.JTextField();
        txtPhn_Add = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        txtCnic_Add = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        lblAddCustomerError = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress_Add = new javax.swing.JTextArea();

        jPanel1.setLayout(null);

        jLabel6.setText("Enter Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 140, 70, 30);

        jLabel7.setText("Enter Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 260, 90, 30);

        jLabel8.setText("Enter Phone Number");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 180, 120, 30);

        txtName_Add.setToolTipText("Enter Customer Name");
        txtName_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName_AddActionPerformed(evt);
            }
        });
        txtName_Add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtName_AddKeyPressed(evt);
            }
        });
        jPanel1.add(txtName_Add);
        txtName_Add.setBounds(390, 140, 370, 30);

        txtPhn_Add.setToolTipText("Enter Customer Phone Number. Format: 03xxxxxxxxx");
        txtPhn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhn_AddActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhn_Add);
        txtPhn_Add.setBounds(390, 180, 370, 30);

        btnAddCustomer.setText("Add");
        btnAddCustomer.setToolTipText("Add Customer");
        btnAddCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddCustomer);
        btnAddCustomer.setBounds(510, 430, 130, 40);

        txtCnic_Add.setToolTipText("Enter Customer CNIC. Format: xxxxx-xxxxxxx-x");
        txtCnic_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnic_AddActionPerformed(evt);
            }
        });
        txtCnic_Add.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                txtCnic_AddAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        jPanel1.add(txtCnic_Add);
        txtCnic_Add.setBounds(390, 220, 370, 30);

        jLabel49.setText("Enter CNIC");
        jPanel1.add(jLabel49);
        jLabel49.setBounds(310, 220, 70, 30);

        lblAddCustomerError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lblAddCustomerError);
        lblAddCustomerError.setBounds(350, 390, 440, 30);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add emp.png"))); // NOI18N
        jPanel1.add(jLabel65);
        jLabel65.setBounds(390, 0, 100, 130);

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setText("ADD CUSTOMER");
        jPanel1.add(jLabel66);
        jLabel66.setBounds(500, 50, 220, 50);

        txtAddress_Add.setColumns(20);
        txtAddress_Add.setRows(5);
        txtAddress_Add.setToolTipText("Enter Customer Address");
        jScrollPane1.setViewportView(txtAddress_Add);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(390, 260, 370, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtName_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName_AddActionPerformed
        // TODO add your handling code here:
        txtName_Add.nextFocus();
        lblAddCustomerError.setText("");
    }//GEN-LAST:event_txtName_AddActionPerformed

    private void txtName_AddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtName_AddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_AddKeyPressed

    private void txtPhn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhn_AddActionPerformed
        // TODO add your handling code here:
        txtPhn_Add.nextFocus();
        lblAddCustomerError.setText("");
    }//GEN-LAST:event_txtPhn_AddActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        addCustomer();
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void txtCnic_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnic_AddActionPerformed
        // TODO add your handling code here:4
        txtCnic_Add.nextFocus();
        lblAddCustomerError.setText("");
    }//GEN-LAST:event_txtCnic_AddActionPerformed

    private void txtCnic_AddAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtCnic_AddAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnic_AddAncestorMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddCustomerError;
    private javax.swing.JTextArea txtAddress_Add;
    private javax.swing.JTextField txtCnic_Add;
    private javax.swing.JTextField txtName_Add;
    private javax.swing.JTextField txtPhn_Add;
    // End of variables declaration//GEN-END:variables

    /**
     * Function to add customer
     */
    private void addCustomer() {
        String name = txtName_Add.getText();
        String address = txtAddress_Add.getText();
        String phnNo = txtPhn_Add.getText();
        String cnic = txtCnic_Add.getText();

        if (!validation.isEmpty(name)) {
            if (!validation.isEmpty(address)) {
                if (validation.isValidPhoneNo(phnNo)) {
                    if (validation.isValidCnic(cnic)) {
                        Customer customer = new Customer();
                        customer.setName(name);
                        customer.setAddress(address);
                        customer.setNumber(phnNo);
                        customer.setCnic(cnic);
                        if (dataManager.getCustomerManager().addCustomer(customer)) {
                            clearValues();
                            dialog.show("Successfully added New customer");
                            lblAddCustomerError.setText("");
                        } else {
                            dialog.show("Customer Already Exists");
                            lblAddCustomerError.setText("Customer Already Exists");
                        }
                    } else {
                        dialog.show("Invalid CNIC Format. Format: xxxxx-xxxxxxx-x");
                        lblAddCustomerError.setText("Invalid CNIC Format. Format: xxxxx-xxxxxxx-x");
                    }
                } else {
                    dialog.show("Wrong Phnone No. Format: 03xxxxxxxxx");
                    lblAddCustomerError.setText("Wrong Phnone No. Format: 03xxxxxxxxx");
                }
            } else {
                dialog.show("Please Specify Address.");
                lblAddCustomerError.setText("Please Specify Address.");
            }
        } else {
            dialog.show("Please Specify Name");
            lblAddCustomerError.setText("Please Specify Name");
        }
    }

    /**
     * Function to clear field values
     */
    void clearValues() {
        txtAddress_Add.setText("");
        txtCnic_Add.setText("");
        txtName_Add.setText("");
        txtPhn_Add.setText("");
    }
}
