/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaceLayer;

import BusinessLogicLayer.Area;
import BusinessLogicLayer.Block;
import BusinessLogicLayer.DataManager;
import BusinessLogicLayer.PropertyCharacteristic;
import BusinessLogicLayer.PropertyManager;
import BusinessLogicLayer.PropertyService;
import BusinessLogicLayer.PropertyType;
import BusinessLogicLayer.Validations;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author arsalan
 */
public class AddPropertySubDetails extends javax.swing.JPanel {

    private Validations validation;
    private PropertyManager propertyManager;
    private ArrayList<Area> areaList;
    private DialogBox dialog;

    /**
     * Creates new form AddPropertySubDetails
     */
    public AddPropertySubDetails() {
        initComponents();
        validation = new Validations();
        propertyManager = DataManager.getInstance().getPropertyManager();
        dialog = new DialogBox();
        configureUI();
        fillAreaDropDown();
    }

    private void configureUI() {
        lblAreaError.setVisible(false);
        lblBlockError.setVisible(false);
        lblCharacteristicError.setVisible(false);
        lblPropertyError.setVisible(false);
        lblServiceError.setVisible(false);
    }

    private void disableBlockPortion() {
        txtBlock.setEnabled(false);
        btnAddBlock.setEnabled(false);
        spinLoadShed.setEnabled(false);
        spinPrice.setEnabled(false);
        showBlockLabel("No Area Found", 0);
    }

    private void enableBlockPortion() {
        txtBlock.setEnabled(true);
        btnAddBlock.setEnabled(true);
        spinLoadShed.setEnabled(true);
        spinPrice.setEnabled(true);
        showBlockLabel("", 0);
    }

    private void showAreaLabel(String text, int mode) {
        dialog.show(text);
        lblAreaError.setText(text);
        lblAreaError.setForeground((mode == 0) ? Color.red : Color.black);
        lblAreaError.setVisible(true);
    }

    private void showBlockLabel(String text, int mode) {
        dialog.show(text);
        lblBlockError.setText(text);
        lblBlockError.setForeground((mode == 0) ? Color.red : Color.black);
        lblBlockError.setVisible(true);
    }

    private void showCharacteristicLabel(String text, int mode) {
        lblCharacteristicError.setText(text);
        dialog.show(text);
        lblCharacteristicError.setForeground((mode == 0) ? Color.red : Color.black);
        lblCharacteristicError.setVisible(true);
    }

    private void showPropertyLabel(String text, int mode) {
        lblPropertyError.setText(text);
        dialog.show(text);
        lblPropertyError.setForeground((mode == 0) ? Color.red : Color.black);
        lblPropertyError.setVisible(true);
    }

    private void showServiceLabel(String text, int mode) {
        lblServiceError.setText(text);
        dialog.show(text);
        lblServiceError.setForeground((mode == 0) ? Color.red : Color.black);
        lblServiceError.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtService = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPropertyType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAddPropertyType = new javax.swing.JButton();
        lblPropertyError = new javax.swing.JLabel();
        txtCharacteristic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBlock = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbArea = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        lblBlockError = new javax.swing.JLabel();
        btnAddBlock = new javax.swing.JButton();
        btnAddService = new javax.swing.JButton();
        lblServiceError = new javax.swing.JLabel();
        btnAddCharacteristic = new javax.swing.JButton();
        btnAddArea = new javax.swing.JButton();
        lblCharacteristicError = new javax.swing.JLabel();
        lblAreaError = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        spinPrice = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinLoadShed = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        jPanel10.setLayout(null);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setText("ADD PROPERTY DETAILS");
        jPanel10.add(jLabel59);
        jLabel59.setBounds(400, 10, 340, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Property Characteristic");
        jPanel10.add(jLabel1);
        jLabel1.setBounds(10, 70, 150, 30);

        txtService.setToolTipText("Enter Service Name");
        txtService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceActionPerformed(evt);
            }
        });
        jPanel10.add(txtService);
        txtService.setBounds(180, 250, 300, 30);

        jLabel4.setText("Service Name");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(80, 250, 90, 30);

        txtArea.setToolTipText("Enter Area Name");
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });
        jPanel10.add(txtArea);
        txtArea.setBounds(640, 110, 310, 30);

        jLabel6.setText("Area Name");
        jPanel10.add(jLabel6);
        jLabel6.setBounds(570, 110, 70, 30);

        txtPropertyType.setToolTipText("Enter Property Type");
        txtPropertyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropertyTypeActionPerformed(evt);
            }
        });
        jPanel10.add(txtPropertyType);
        txtPropertyType.setBounds(180, 390, 300, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Property Type");
        jPanel10.add(jLabel8);
        jLabel8.setBounds(10, 360, 140, 30);

        btnAddPropertyType.setText("Add Property Type");
        btnAddPropertyType.setToolTipText("Add Property Type");
        btnAddPropertyType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPropertyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPropertyTypeActionPerformed(evt);
            }
        });
        jPanel10.add(btnAddPropertyType);
        btnAddPropertyType.setBounds(190, 430, 220, 30);

        lblPropertyError.setForeground(new java.awt.Color(102, 102, 0));
        lblPropertyError.setText("Property Type Already Exist");
        jPanel10.add(lblPropertyError);
        lblPropertyError.setBounds(180, 360, 300, 30);

        txtCharacteristic.setToolTipText("Enter Characteristic Name");
        txtCharacteristic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCharacteristicActionPerformed(evt);
            }
        });
        jPanel10.add(txtCharacteristic);
        txtCharacteristic.setBounds(180, 110, 300, 30);

        jLabel10.setText("Characteristic Name");
        jPanel10.add(jLabel10);
        jLabel10.setBounds(60, 110, 120, 30);

        txtBlock.setToolTipText("Enter Block Name");
        txtBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlockActionPerformed(evt);
            }
        });
        jPanel10.add(txtBlock);
        txtBlock.setBounds(650, 300, 300, 30);

        jLabel12.setText("Block Name");
        jPanel10.add(jLabel12);
        jLabel12.setBounds(580, 300, 70, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Services");
        jPanel10.add(jLabel13);
        jLabel13.setBounds(10, 220, 70, 30);

        jLabel14.setText("Property Type");
        jPanel10.add(jLabel14);
        jLabel14.setBounds(80, 390, 80, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Area Details");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(520, 70, 100, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Block Details");
        jPanel10.add(jLabel16);
        jLabel16.setBounds(520, 220, 90, 30);

        cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaActionPerformed(evt);
            }
        });
        jPanel10.add(cmbArea);
        cmbArea.setBounds(650, 260, 300, 30);

        jLabel17.setText("Area");
        jPanel10.add(jLabel17);
        jLabel17.setBounds(610, 260, 40, 30);

        lblBlockError.setForeground(new java.awt.Color(102, 102, 0));
        lblBlockError.setText("Block Already Exist");
        jPanel10.add(lblBlockError);
        lblBlockError.setBounds(650, 220, 280, 30);

        btnAddBlock.setText("Add Block Name");
        btnAddBlock.setToolTipText("Add Block Name");
        btnAddBlock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBlockActionPerformed(evt);
            }
        });
        jPanel10.add(btnAddBlock);
        btnAddBlock.setBounds(670, 400, 220, 30);

        btnAddService.setText("Add Service");
        btnAddService.setToolTipText("Add Service");
        btnAddService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });
        jPanel10.add(btnAddService);
        btnAddService.setBounds(190, 290, 220, 30);

        lblServiceError.setForeground(new java.awt.Color(102, 102, 0));
        lblServiceError.setText("Service Already Exist");
        jPanel10.add(lblServiceError);
        lblServiceError.setBounds(180, 220, 300, 30);

        btnAddCharacteristic.setText("Add Characteristic");
        btnAddCharacteristic.setToolTipText("Add Characteristic");
        btnAddCharacteristic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCharacteristic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCharacteristicActionPerformed(evt);
            }
        });
        jPanel10.add(btnAddCharacteristic);
        btnAddCharacteristic.setBounds(190, 160, 220, 30);

        btnAddArea.setText("Add Area Name");
        btnAddArea.setToolTipText("Add Area Name");
        btnAddArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAreaActionPerformed(evt);
            }
        });
        jPanel10.add(btnAddArea);
        btnAddArea.setBounds(670, 160, 220, 30);

        lblCharacteristicError.setForeground(new java.awt.Color(102, 102, 0));
        lblCharacteristicError.setText("Property Characteristic Already Exist");
        jPanel10.add(lblCharacteristicError);
        lblCharacteristicError.setBounds(180, 70, 290, 30);

        lblAreaError.setForeground(new java.awt.Color(102, 102, 0));
        lblAreaError.setText("Area Already Exist");
        jPanel10.add(lblAreaError);
        lblAreaError.setBounds(650, 70, 290, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator1);
        jSeparator1.setBounds(500, 60, 20, 450);
        jPanel10.add(jSeparator2);
        jSeparator2.setBounds(0, 210, 1040, 20);
        jPanel10.add(jSeparator3);
        jSeparator3.setBounds(0, 340, 500, 30);
        jPanel10.add(jSeparator4);
        jSeparator4.setBounds(0, 60, 1040, 20);

        spinPrice.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1000), Integer.valueOf(1000), null, Integer.valueOf(1000)));
        jPanel10.add(spinPrice);
        spinPrice.setBounds(650, 350, 100, 30);

        jLabel3.setText("Price Per Ft");
        jPanel10.add(jLabel3);
        jLabel3.setBounds(580, 350, 70, 30);

        spinLoadShed.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        jPanel10.add(spinLoadShed);
        spinLoadShed.setBounds(900, 350, 50, 30);

        jLabel2.setText("Load Shedding Hours");
        jPanel10.add(jLabel2);
        jLabel2.setBounds(760, 350, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1043, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCharacteristicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCharacteristicActionPerformed
        addCharacteristic();
    }//GEN-LAST:event_btnAddCharacteristicActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        // TODO add your handling code here:
        addService();
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnAddPropertyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPropertyTypeActionPerformed
        // TODO add your handling code here:
        addPropertyType();
    }//GEN-LAST:event_btnAddPropertyTypeActionPerformed

    private void btnAddAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAreaActionPerformed
        // TODO add your handling code here:
        addArea();
    }//GEN-LAST:event_btnAddAreaActionPerformed

    private void btnAddBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBlockActionPerformed
        // TODO add your handling code here:
        addBlock();
    }//GEN-LAST:event_btnAddBlockActionPerformed

    private void cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbAreaActionPerformed

    private void txtCharacteristicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCharacteristicActionPerformed
        // TODO add your handling code here:
        btnAddCharacteristicActionPerformed(evt);
    }//GEN-LAST:event_txtCharacteristicActionPerformed

    private void txtServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceActionPerformed
        // TODO add your handling code here:
        btnAddServiceActionPerformed(evt);
    }//GEN-LAST:event_txtServiceActionPerformed

    private void txtPropertyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropertyTypeActionPerformed
        // TODO add your handling code here:
        btnAddPropertyTypeActionPerformed(evt);
    }//GEN-LAST:event_txtPropertyTypeActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
        btnAddAreaActionPerformed(evt);
    }//GEN-LAST:event_txtAreaActionPerformed

    private void txtBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlockActionPerformed
        // TODO add your handling code here:
        txtBlock.nextFocus();
    }//GEN-LAST:event_txtBlockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArea;
    private javax.swing.JButton btnAddBlock;
    private javax.swing.JButton btnAddCharacteristic;
    private javax.swing.JButton btnAddPropertyType;
    private javax.swing.JButton btnAddService;
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAreaError;
    private javax.swing.JLabel lblBlockError;
    private javax.swing.JLabel lblCharacteristicError;
    private javax.swing.JLabel lblPropertyError;
    private javax.swing.JLabel lblServiceError;
    private javax.swing.JSpinner spinLoadShed;
    private javax.swing.JSpinner spinPrice;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtBlock;
    private javax.swing.JTextField txtCharacteristic;
    private javax.swing.JTextField txtPropertyType;
    private javax.swing.JTextField txtService;
    // End of variables declaration//GEN-END:variables

    private void addCharacteristic() {
        // TODO add your handling code here:
        String text = txtCharacteristic.getText();
        if (!validation.isEmpty(text)) {
            PropertyCharacteristic characteristic = new PropertyCharacteristic();
            characteristic.setCharacteristicName(text);
            if (propertyManager.addCharacteristic(characteristic)) {
                dialog.show("Characteristic Added Successfully");
                lblCharacteristicError.setText("");
                txtCharacteristic.setText("");
            } else {
                showCharacteristicLabel("Characteristic Already Exists", 0);
            }
        } else {
            showCharacteristicLabel("Please Enter Characteristic", 0);
        }
    }

    private void addService() {
        String text = txtService.getText();
        if (!validation.isEmpty(text)) {
            PropertyService service = new PropertyService();
            service.setServiceName(text);
            if (propertyManager.addService(service)) {
                dialog.show("Service Added Successfully");
                lblServiceError.setText("");
                txtService.setText("");
            } else {
                showServiceLabel("Service Already Exists", 0);
            }
        } else {
            showServiceLabel("Please Enter Service", 0);
        }
    }

    private void addPropertyType() {
        String text = txtPropertyType.getText();
        if (!validation.isEmpty(text)) {
            PropertyType type = new PropertyType();
            type.setTypeName(text);
            if (propertyManager.addType(type)) {
                dialog.show("Property Type Added Successfully");
                lblPropertyError.setText("");
                txtPropertyType.setText("");
            } else {
                showPropertyLabel("Property Type Already Exists", 0);

            }
        } else {
            showPropertyLabel("Please Enter Property Type", 0);
        }
    }

    private void addArea() {
        String text = txtArea.getText();
        if (!validation.isEmpty(text)) {
            Area area = new Area();
            area.setAreaName(text);
            if (propertyManager.addArea(area)) {
                dialog.show("Area Added Successfully");
                lblAreaError.setText("");
                txtArea.setText("");
                fillAreaDropDown();
            } else {
                showAreaLabel("Area Already Exists", 0);
            }
        } else {
            showAreaLabel("Please Enter Area", 0);
        }
    }

    private void addBlock() {
        int index = cmbArea.getSelectedIndex();
        if (index >= 0) {
            String text = txtBlock.getText();
            if (!validation.isEmpty(text)) {
                Block block = new Block();
                block.setBlockName(text);
                block.setNoOfHourOfLoadShed((int) spinLoadShed.getValue());
                block.setPricePerFt((int) spinPrice.getValue());
                block.setAreaId(areaList.get(index).getAreaId());
                if (propertyManager.addBlock(block)) {
                    dialog.show("Block Added Successfully");
                    lblBlockError.setText("");
                    txtBlock.setText("");
                } else {
                    showBlockLabel("Block Already Exists", 0);
                }
            } else {
                showBlockLabel("Please Enter Block", 0);
            }
        } else {
            showBlockLabel("Please Select Area", 0);
        }
    }

    public void fillAreaDropDown() {
        areaList = propertyManager.getAreas();
        cmbArea.removeAllItems();
        if (areaList.size() > 0) {
            Area area;
            enableBlockPortion();

            for (int i = 0; i < areaList.size(); i++) {
                area = areaList.get(i);
                cmbArea.addItem(area.getAreaName());
            }
        } else {
            disableBlockPortion();
        }
    }
}
