/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaceLayer;

import javax.swing.JTabbedPane;

/**
 *
 * @author arsalan
 */
public class ManageProperty extends javax.swing.JPanel {

    private AddProperty addProperty = new AddProperty();
    private UpdateProperty updateProperty = new UpdateProperty();
    private AddPropertySubDetails addPropertySubDetails = new AddPropertySubDetails();
    private UpdatePropertySubDetails updatePropertySubDetails = new UpdatePropertySubDetails();

    /**
     * Creates new form Clothes
     */
    public ManageProperty() {
        initComponents();
        propertyTabBar.add(addProperty, "Add Property");
        propertyTabBar.add(updateProperty, "Update Property");
        propertyTabBar.add(addPropertySubDetails, "Add Sub Details");
        propertyTabBar.add(updatePropertySubDetails, "Update Sub Details");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertyTabBar = new javax.swing.JTabbedPane();

        propertyTabBar.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        propertyTabBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                propertyTabBarStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(propertyTabBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(propertyTabBar, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void propertyTabBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_propertyTabBarStateChanged
        // TODO add your handling code here:
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        switch (index) {
            case 0:
                addProperty.fillAllDropDown();
                break;
            case 1:
                break;
            case 2:
                addPropertySubDetails.fillAreaDropDown();
                break;
            case 3:
                updatePropertySubDetails.fillAllDropDownValues();
                break;
        }
    }//GEN-LAST:event_propertyTabBarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane propertyTabBar;
    // End of variables declaration//GEN-END:variables
}
