/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaceLayer;

import BusinessLogicLayer.DataManager;
import BusinessLogicLayer.Validations;
import java.awt.Color;

/**
 *
 * @author arsalan
 */
public class UpdatePassword extends javax.swing.JPanel {

    private Validations validation;
    private DataManager dataManager;
    private DialogBox dialog;

    /**
     * Creates new form UpdatePassword
     */
    public UpdatePassword() {
        initComponents();
        clearUpdatePass();
        setColor();
        validation = new Validations();
        dataManager = DataManager.getInstance();
        dialog = new DialogBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtOldPass_UPass = new javax.swing.JPasswordField();
        txtNewPass_UPass = new javax.swing.JPasswordField();
        jLabel38 = new javax.swing.JLabel();
        btnUpdatePass = new javax.swing.JButton();
        txtConfPass_UPass = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        lblUPassInvalidPass = new javax.swing.JLabel();
        lblPassMatch = new javax.swing.JLabel();
        updatePassStatus = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();

        jPanel8.setLayout(null);

        jLabel37.setText("Old Password: ");
        jPanel8.add(jLabel37);
        jLabel37.setBounds(360, 150, 100, 30);

        txtOldPass_UPass.setToolTipText("Enter Old Password");
        txtOldPass_UPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPass_UPassActionPerformed(evt);
            }
        });
        jPanel8.add(txtOldPass_UPass);
        txtOldPass_UPass.setBounds(470, 150, 240, 30);

        txtNewPass_UPass.setToolTipText("Enter New Password");
        txtNewPass_UPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPass_UPassActionPerformed(evt);
            }
        });
        jPanel8.add(txtNewPass_UPass);
        txtNewPass_UPass.setBounds(470, 210, 240, 30);

        jLabel38.setText("New Password: ");
        jPanel8.add(jLabel38);
        jLabel38.setBounds(360, 210, 100, 30);

        btnUpdatePass.setText("Update");
        btnUpdatePass.setToolTipText("Update Password");
        btnUpdatePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassActionPerformed(evt);
            }
        });
        jPanel8.add(btnUpdatePass);
        btnUpdatePass.setBounds(550, 340, 80, 40);

        txtConfPass_UPass.setToolTipText("Re Enter New Password");
        txtConfPass_UPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfPass_UPassActionPerformed(evt);
            }
        });
        jPanel8.add(txtConfPass_UPass);
        txtConfPass_UPass.setBounds(470, 280, 240, 30);

        jLabel19.setText("Confirm Password:");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(360, 280, 110, 30);

        lblUPassInvalidPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUPassInvalidPass.setText("Wrong Password!!!");
        jPanel8.add(lblUPassInvalidPass);
        lblUPassInvalidPass.setBounds(470, 180, 320, 30);

        lblPassMatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassMatch.setText("Password Doesnot Match!!!!!");
        jPanel8.add(lblPassMatch);
        lblPassMatch.setBounds(470, 240, 250, 40);

        updatePassStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatePassStatus.setText("Done");
        jPanel8.add(updatePassStatus);
        updatePassStatus.setBounds(460, 380, 430, 40);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pass.png"))); // NOI18N
        jPanel8.add(jLabel58);
        jLabel58.setBounds(330, 10, 130, 120);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setText("UPDATE PASSWORD");
        jPanel8.add(jLabel59);
        jLabel59.setBounds(480, 50, 340, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1043, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtOldPass_UPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPass_UPassActionPerformed
        // TODO add your handling code here:
        txtOldPass_UPass.nextFocus();
        updatePassStatus.setVisible(false);
    }//GEN-LAST:event_txtOldPass_UPassActionPerformed

    private void txtNewPass_UPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPass_UPassActionPerformed
        // TODO add your handling code here:
        txtNewPass_UPass.nextFocus();
        updatePassStatus.setVisible(false);
    }//GEN-LAST:event_txtNewPass_UPassActionPerformed

    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassActionPerformed
        updatePassword();
    }//GEN-LAST:event_btnUpdatePassActionPerformed

    private void txtConfPass_UPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfPass_UPassActionPerformed
        // TODO add your handling code here:
        updatePassStatus.setVisible(false);
        btnUpdatePassActionPerformed(evt);
    }//GEN-LAST:event_txtConfPass_UPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdatePass;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblPassMatch;
    private javax.swing.JLabel lblUPassInvalidPass;
    private javax.swing.JPasswordField txtConfPass_UPass;
    private javax.swing.JPasswordField txtNewPass_UPass;
    private javax.swing.JPasswordField txtOldPass_UPass;
    private javax.swing.JLabel updatePassStatus;
    // End of variables declaration//GEN-END:variables

    /**
     * Function to update password
     */
    private void updatePassword() {
        String oldPass = txtOldPass_UPass.getText();
        String pass = txtNewPass_UPass.getText();
        String secPass = txtConfPass_UPass.getText();
        if ((!validation.isEmpty(oldPass)) && dataManager.isValidPassword(oldPass)) {
            if (!validation.isEmpty(pass) && !validation.isEmpty(secPass) && validation.isEquals(pass, secPass)) {
                updatePassStatus.setVisible(true);
                if (dataManager.getAgentManager().updatePassword(pass)) {
                    clearUpdatePass();
                    lblPassMatch.setForeground(Color.black);
                    dialog.show("Password Successfully Updated");
                    updatePassStatus.setText("");
                } else {
                    dialog.show("Error in Updating Password");
                    updatePassStatus.setText("Error in Updating Password");
                    lblPassMatch.setForeground(Color.red);
                }
            } else {
                updatePassStatus.setVisible(false);
                lblPassMatch.setVisible(true);
                lblUPassInvalidPass.setVisible(false);
            }
        } else {
            updatePassStatus.setVisible(false);
            lblPassMatch.setVisible(false);
            lblUPassInvalidPass.setVisible(true);
        }
    }

    /**
     * clear items of update password
     */
    private void clearUpdatePass() {
        txtOldPass_UPass.setText("");
        txtNewPass_UPass.setText("");
        txtConfPass_UPass.setText("");
        lblPassMatch.setVisible(false);
        lblUPassInvalidPass.setVisible(false);
    }

    /**
     * set color of all labels
     */
    public void setColor() {
        lblUPassInvalidPass.setForeground(Color.red);
        lblPassMatch.setForeground(Color.red);
        updatePassStatus.setVisible(false);
    }
}
